# Generated by Django 3.0.7 on 2020-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=4)),
                ('url', models.TextField()),
                ('created', models.DateTimeField()),
                ('last_visited', models.DateTimeField()),
                ('times_visited', models.BigIntegerField()),
            ],
        ),
    ]
