# Generated by Django 3.0.7 on 2020-07-04 12:11

from django.db import migrations, models
import url.lib.generator


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20200704_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default=url.lib.generator.random_string, max_length=4, unique=True),
        ),
    ]
