# Generated by Django 3.0.7 on 2020-07-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_urllog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='urllog',
            name='country',
        ),
    ]
