# Generated by Django 3.0.7 on 2020-07-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_auto_20200706_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllog',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
