# Generated by Django 3.0.7 on 2020-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0006_auto_20200706_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
